# Generated by Django 5.2.8 on 2025-11-06 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ['-uploated_at']},
        ),
        migrations.RenameField(
            model_name='files',
            old_name='uploaded_at',
            new_name='uploated_at',
        ),
    ]
